dist: trusty
notifications:
  slack: ventureum-team:DSE8wxmLTenq0Yz17BrYBWg9
language: node_js
node_js:
- 8
fail_fast: true
script:
- npm test
- wget https://s3.amazonaws.com/chainsfer-config/dev/.env
- npm run build
deploy:
  provider: s3
  skip_cleanup: true
  cache_control: "no-cache"
  access_key_id: AKIAIFWICYKK6GWUDRMA
  secret_access_key: $S3_SECRET
  bucket: www.chainsfer.io
  local_dir: build
  region: us-east-1
  acl: public_read
  on:
    repo: ventureum/Chainsfer
true:
  branch: master
